// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgQyOTjTUiUxMVKZ8N1LCDWwohs9p1Xy4',
    appId: '1:336456206957:web:81d667e42336faffe24d64',
    messagingSenderId: '336456206957',
    projectId: 'firbase-test-5aeb3',
    authDomain: 'firbase-test-5aeb3.firebaseapp.com',
    storageBucket: 'firbase-test-5aeb3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGLx-8SgW-O6Iwa4lehjLQerpHvkGM_Iw',
    appId: '1:336456206957:android:fbbb3e9827a94547e24d64',
    messagingSenderId: '336456206957',
    projectId: 'firbase-test-5aeb3',
    storageBucket: 'firbase-test-5aeb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL8Pi4fqlaCpCB-kOP3I0WA8eQKCYDhbw',
    appId: '1:336456206957:ios:eb8c2750e699ebbee24d64',
    messagingSenderId: '336456206957',
    projectId: 'firbase-test-5aeb3',
    storageBucket: 'firbase-test-5aeb3.appspot.com',
    iosBundleId: 'com.example.firebaseTestLast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL8Pi4fqlaCpCB-kOP3I0WA8eQKCYDhbw',
    appId: '1:336456206957:ios:eb8c2750e699ebbee24d64',
    messagingSenderId: '336456206957',
    projectId: 'firbase-test-5aeb3',
    storageBucket: 'firbase-test-5aeb3.appspot.com',
    iosBundleId: 'com.example.firebaseTestLast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgQyOTjTUiUxMVKZ8N1LCDWwohs9p1Xy4',
    appId: '1:336456206957:web:c52206d2737d9635e24d64',
    messagingSenderId: '336456206957',
    projectId: 'firbase-test-5aeb3',
    authDomain: 'firbase-test-5aeb3.firebaseapp.com',
    storageBucket: 'firbase-test-5aeb3.appspot.com',
  );

}